### PR TITLE
fix(auth): added scenario to use with itop regression

### PR DESCRIPTION
**Pull request by JigSawFr**
This commit fix regression: https://sourceforge.net/p/itop/tickets/1061/ as you are unable to use basic auth with this version

### CODE REVIEW

**Comment by vbkunin** [comment]
@JigSawFr thanks! 👍

**Comment by JigSawFr** [comment]
Thank you sir ! :)

**Comment by JigSawFr** [comment]
@vbkunin can you push fix to npm ? thanks

**Comment by vbkunin** [comment]
@JigSawFr of course! I don't know why I haven't done it yet.

**Comment by JigSawFr** [comment]
Great ! I can now remote git from my Dockerfile,
Thank you @vbkunin 👍

**Pull request merged**
